### ISSUE TITLE
Connectionleak caused by library

### ISSUE THREAD

**Issue by Wegi** [n2o/postgres-listener#1]
The library leaks connections. Here is the output it produced in the argweb project:

```
aggregator_1          | Nov 07, 2017 3:28:51 PM com.impossibl.postgres.jdbc.ThreadedHousekeeper$HousekeeperReference cleanup
aggregator_1          | WARNING: Cleaning up leaked connection ( jdbc:pgsql://dbas-db/discussion )
aggregator_1          | Allocation occurred @
aggregator_1          |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
aggregator_1          |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
aggregator_1          |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
aggregator_1          |   at java.lang.reflect.Method.invoke(Method.java:498)
aggregator_1          |   at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
aggregator_1          |   at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:313)
aggregator_1          |   at postgres_listener.core$connection.invokeStatic(core.clj:42)
aggregator_1          |   at postgres_listener.core$connection.invoke(core.clj:36)
aggregator_1          |   at postgres_listener.core$arm_listener.invokeStatic(core.clj:54)
aggregator_1          |   at postgres_listener.core$arm_listener.invoke(core.clj:45)
  ... <Stacktrace to the calling functions>
```

**Comment by n2o** [comment]
The credentials changed for the database, which is why it might loose the connection.

**Comment by n2o** [comment]
It has shown, that the "leaked-connection" error was an issue of the calling function in the external project. Several listeners were armed with some code like this:

```clojure
(pgl/arm-listener f1 "event1")
(pgl/arm-listener f2 "event2")
(pgl/arm-listener f3 "event3")
```
But if we have these side effects in Clojure, it is advised to use some special functions for it to guarantee proper functionality, for example [doseq](https://clojuredocs.org/clojure.core/doseq). We solved this issue by surrounding the listeners with `doseq` like this:

```clojure
(doseq [[f event] [[f1 "event1"]
                   [f2 "event2"]]]
  (pgl/arm-listener f event))
```

**Comment by tiensonqin** [comment]
@n2o I got this problem too.
```
Mar 05, 2019 7:51:21 AM com.impossibl.postgres.jdbc.ThreadedHousekeeper$HousekeeperReference cleanup
WARNING: Cleaning up leaked statement
Allocation occurred @
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
  at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:438)
  at recommendations.pg_listener$arm_listener.invokeStatic(pg_listener.clj:61)
  at recommendations.pg_listener$arm_listener.invoke(pg_listener.clj:52)
  at recommendations.pg_listener$start_BANG_.invokeStatic(pg_listener.clj:85)
  at recommendations.pg_listener$start_BANG_.invoke(pg_listener.clj:75)

```
